name: Docker

on:
  push:
    branches:
      - 'main'
      - 'master'

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # This GitHub Actions step sets up QEMU (Quick Emulator) on the runner using the docker/setup-qemu-action action.
      # QEMU is an open-source hardware emulator and virtualization tool that enables developers to run and test software on different CPU architectures. 
      # It is often used in conjunction with Docker to build and test multi-architecture container images.
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      
      # Docker Buildx is an experimental feature in Docker that extends the functionality of the traditional Docker build command, enabling developers to build multi-architecture container images using a single Dockerfile and command.
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Build and push
        uses: docker/build-push-action@v4
        with:
          push: true
          tags: yriahi/tf-utils:latest          
          # 
          # Cache Docker layers to speed up build times:
          # Utilize the BuildKit cache to speed up consecutive builds by caching intermediate Docker layers.
          # This can significantly reduce build times, especially when only a few layers have changed between builds.
          cache-from: type=gha
          cache-to: type=gha,mode=max
