name: Release Drafter

on:
  push:
    branches:
      - main # You can also use other branch names or tags instead of "main"
      - master # You can also use other branch names or tags instead of "main"

permissions:
  contents: write
  packages: write  
  issues:  read
 
jobs:
  release-drafter:
    runs-on: ubuntu-latest
    steps:
      - name: Draft a new release
        uses: release-drafter/release-drafter@v5
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
